# kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: maria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: marianayeli/copichat:latest   # Reemplaza con tu imagen DockerHub
        imagePullPolicy: IfNotPresent           # Evita bajar la imagen si ya existe
        envFrom:
            - secretRef:
                name: microservice-secret               # Cargar todo el Secret como variables de entorno