# kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copichat
  namespace: marianayeli
spec:
  replicas: 2
  selector:
    matchLabels:
      app: copichat
  template:
    metadata:
      labels:
        app: copichat
    spec:
      containers:
        - name: copichat
          image: marianayeli/copiback:latest
          imagePullPolicy: IfNotPresent           # Evita bajar la imagen si ya existe
          envFrom:
            - secretRef:
                name: credentials               # Cargar todo el Secret como variables de entorno