# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: copichat
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXdpbGQtdW5pb24tYTRhdXNlNmpwcG9vbGVyLnVzLWVhc3QtMS5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmU=
  DATABASE_USERNAME: bmVvbmRiX293bmVy
  DATABASE_PASSWORD: bnBnX2NEeEwzZGJHVjh0Vw==
  RAPIDAPI_URL: aHR0cHM6Ly9jb3BpbG90NS5wLnJhcGlkYXBpLmNvbS9jb3BpbG90
  RAPIDAPI_HOST: Y29waWxvdDUucC5yYXBpZGFwaS5jb20=
  RAPIDAPI_APIKEY: YzIxM2YxZmJhZG1zaDMyZjkyZDc2NWFkOTQ5ZnAxOGNjNDBqc25hMTJhNjEzNDJiZjE=


#spring.r2dbc.url=r2dbc:postgresql://ep-wild-union-a4ause6j-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
#spring.r2dbc.username=neondb_owner
#spring.r2dbc.password=npg_cDxL3daGV8tW

# echo -n npg_cDxL3daGV8tW | base64
# echo -n "my-password" | base64
# echo "bXktdXNlcg==" | base64 --decode