apiVersion: v1
kind: Secret
metadata:
  name: copichat-secret
  namespace: copichat
type: Opaque
data:
  database_url: cnJkYmM6cG9zdGdyZXNxbDovL2VwLXdpbGQtdW5pb24tYTRhdXNlNmpwLXBvb2xlci51cy1lYXN0LTEuYXdzLm5lb24udGVjaC9uZW9uZGI/c3NsbW9kZT1yZXF1aXJl
  database_username: bmVvbmRiX293bmVy
  database_password: bnBnX2NEeEwzZGFHVjh0Vw==
  port: ODA4Ng==
