# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: microservice-secret
  namespace: maria
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXdpbGQtdW5pb24tYTRhdXNlNmotcG9vbGVyLnVzLWVhc3QtMS5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmUmY2hhbm5lbF9iaW5kaW5nPXJlcXVpcmU=
  DATABASE_USERNAME: bmVvbmRiX293bmVy
  DATABASE_PASSWORD: bnBnX2NEeEwzZGFHVjh0Vw==
  RAPIDAPI_URL: aHR0cHM6Ly9jb3BpbG90NS5wLnJhcGlkYXBpLmNvbS9jb3BpbG90
  RAPIDAPI_HOST: Y29waWxvdDUucC5yYXBpZGFwaS5jb20=
  RAPIDAPI_APIKEY: YzIxM2YxZmJhZG1zaDMyZjkyZDc2NWFkOTQ5ZnAxOGNjNDBqc25hMTJhNjEzNDJiZjE=

# echo -n "ep-wild-union-a4ause6j-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require" | base64
# echo -n "https://copilot5.p.rapidapi.com/copilot" | base64
# echo "bXktdXNlcg==" | base64 --decode

